### PR TITLE
Implement our own Factor class to mimic R's behavior. 

### PR DESCRIPTION
**Pull request by LTLA**
- [x] tests
- [x] `str` method
- [x] fixes: #50, #26

### CODE REVIEW

**Comment by LTLA** [comment]
Needs #49 to be merged first, because I started work on the wrong branch 🤭

**Comment by LTLA** [comment]
Also looks fine in the `BiocFrame` show method:

```python
>>> biocframe.BiocFrame({ "Aaron": biocframe.Factor([1,2,3,4], levels=["A", "B", "C", "D", "E"]) } )
 BiocFrame with 4
      rows &
  {self.dims[1]}
  column{'s' if
self.dims[1] != 1
     else ''}
┏━━━━━━━━━━━━━━━━┓
┃ Aaron <Factor> ┃
┡━━━━━━━━━━━━━━━━┩
│ B              │
│ C              │
│ E              │
└────────────────┘
```

**Comment by jkanche** [comment]
also fixes: #50

**Comment by jkanche** [comment]
and fixes: #26

**Pull request merged**
